select
    s.loadsmart_id,
    md5(coalesce(s.shipper_name, '__unknown__')) as shipper_key,
    md5(coalesce(s.carrier_name, '__unknown__')) as carrier_key,
    md5(s.lane) as lane_key,
    cast(s.pickup_at as date) as pickup_date,
    cast(s.delivered_at as date) as delivery_date,
    s.quote_at,
    s.booked_at,
    s.sourced_at,
    s.pickup_at,
    s.delivered_at,
    s.book_price,
    s.source_price,
    s.pnl,
    s.mileage,
    s.equipment_type,
    s.carrier_rating,
    s.sourcing_channel,
    s.vip_carrier,
    s.carrier_dropped_us_count,
    s.carrier_on_time_to_pickup,
    s.carrier_on_time_to_delivery,
    s.carrier_on_time_overall,
    s.pickup_appointment_at,
    s.delivery_appointment_at,
    s.has_mobile_app_tracking,
    s.has_macropoint_tracking,
    s.has_edi_tracking,
    s.contracted_load,
    s.load_booked_autonomously,
    s.load_sourced_autonomously,
    s.load_was_cancelled,
    s.is_delivered,
    s.haul_type
from {{ ref('stg_loads') }} s
